#Constraints del Modulo Top
set_property PACKAGE_PIN W5 [get_ports clock]							
	set_property IOSTANDARD LVCMOS33 [get_ports clock]
	create_clock -add -name sys_clk_pin -period 10.000 -waveform {0 5} [get_ports clock]

set_property PACKAGE_PIN T17 [get_ports rx]						
	set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN U17 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U16 [get_ports tx]					
	set_property IOSTANDARD LVCMOS33 [get_ports tx]

#Constraints del Modulo UART
#set_property PACKAGE_PIN W5 [get_ports clock]							
#	set_property IOSTANDARD LVCMOS33 [get_ports clock]
#	create_clock -add -name sys_clk_pin -period 10.000 -waveform {0 5} [get_ports clock]
#set_property PACKAGE_PIN U17 [get_ports reset]						
#	set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property PACKAGE_PIN U18 [get_ports tx_start]						
#	set_property IOSTANDARD LVCMOS33 [get_ports tx_start]
#set_property PACKAGE_PIN T18 [get_ports rx]						
#	set_property IOSTANDARD LVCMOS33 [get_ports rx]
#set_property PACKAGE_PIN V17 [get_ports {din[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
#set_property PACKAGE_PIN V16 [get_ports {din[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
#set_property PACKAGE_PIN W16 [get_ports {din[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
#set_property PACKAGE_PIN W17 [get_ports {din[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
#set_property PACKAGE_PIN W15 [get_ports {din[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
#set_property PACKAGE_PIN V15 [get_ports {din[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
#set_property PACKAGE_PIN W14 [get_ports {din[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[6]}]
#set_property PACKAGE_PIN W13 [get_ports {din[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[7]}]
	
#set_property PACKAGE_PIN U16 [get_ports {dout[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
#set_property PACKAGE_PIN E19 [get_ports {dout[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
#set_property PACKAGE_PIN U19 [get_ports {dout[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
#set_property PACKAGE_PIN V19 [get_ports {dout[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
#set_property PACKAGE_PIN W18 [get_ports {dout[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[4]}]
#set_property PACKAGE_PIN U15 [get_ports {dout[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[5]}]
#set_property PACKAGE_PIN U14 [get_ports {dout[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[6]}]
#set_property PACKAGE_PIN V14 [get_ports {dout[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {dout[7]}]
#set_property PACKAGE_PIN N3 [get_ports tx]					
#	set_property IOSTANDARD LVCMOS33 [get_ports tx]
#set_property PACKAGE_PIN P1 [get_ports tx_done]					
#	set_property IOSTANDARD LVCMOS33 [get_ports tx_done]
#set_property PACKAGE_PIN L1 [get_ports rx_done]					
#	set_property IOSTANDARD LVCMOS33 [get_ports rx_done]


#Constraints del Modulo ALU
#create_clock -name clock -period 10.000

#set_property PACKAGE_PIN V17 [get_ports {a[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
#set_property PACKAGE_PIN V16 [get_ports {a[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
#set_property PACKAGE_PIN W16 [get_ports {a[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
#set_property PACKAGE_PIN W17 [get_ports {a[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
#set_property PACKAGE_PIN W15 [get_ports {a[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[4]}]
#set_property PACKAGE_PIN V15 [get_ports {a[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[5]}]
#set_property PACKAGE_PIN W14 [get_ports {a[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[6]}]
#set_property PACKAGE_PIN W13 [get_ports {a[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {a[7]}]
	
#set_property PACKAGE_PIN V2 [get_ports {b[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
#set_property PACKAGE_PIN T3 [get_ports {b[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
#set_property PACKAGE_PIN T2 [get_ports {b[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
#set_property PACKAGE_PIN R3 [get_ports {b[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
#set_property PACKAGE_PIN W2 [get_ports {b[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[4]}]
#set_property PACKAGE_PIN U1 [get_ports {b[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[5]}]
#set_property PACKAGE_PIN T1 [get_ports {b[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[6]}]
#set_property PACKAGE_PIN R2 [get_ports {b[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {b[7]}]	
	
#set_property PACKAGE_PIN U16 [get_ports {out[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
#set_property PACKAGE_PIN E19 [get_ports {out[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
#set_property PACKAGE_PIN U19 [get_ports {out[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
#set_property PACKAGE_PIN V19 [get_ports {out[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
#set_property PACKAGE_PIN W18 [get_ports {out[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
#set_property PACKAGE_PIN U15 [get_ports {out[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
#set_property PACKAGE_PIN U14 [get_ports {out[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
#set_property PACKAGE_PIN V14 [get_ports {out[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
	
#set_property PACKAGE_PIN U18 [get_ports op[0]]						
#	set_property IOSTANDARD LVCMOS33 [get_ports op[0]]
#set_property PACKAGE_PIN T18 [get_ports op[1]]						
#	set_property IOSTANDARD LVCMOS33 [get_ports op[1]]
#set_property PACKAGE_PIN W19 [get_ports op[2]]						
#	set_property IOSTANDARD LVCMOS33 [get_ports op[2]]	
#set_property PACKAGE_PIN T17 [get_ports op[3]]						
#	set_property IOSTANDARD LVCMOS33 [get_ports op[3]]
#set_property PACKAGE_PIN U17 [get_ports op[4]]						
#	set_property IOSTANDARD LVCMOS33 [get_ports op[4]]
#set_property PACKAGE_PIN W5 [get_ports op[5]]							
#	set_property IOSTANDARD LVCMOS33 [get_ports op[5]]